/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;

import InterfazUsuario.Op1GestorCentro;
import com.mycompany.tallerpoo.*;
/**
 *
 * @author 54345
 */
public class MenuGestorCentro extends javax.swing.JFrame {

    /**
     * Creates new form MenuGestorCentro
     */
    public MenuGestorCentro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        botonOp1 = new javax.swing.JButton();
        botonOp2 = new javax.swing.JButton();
        botonOp3 = new javax.swing.JButton();
        botonOp4 = new javax.swing.JButton();
        botonOp5 = new javax.swing.JButton();
        botonOp6 = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonOp1.setText("Cantidad de pacientes atendidos por un médico en un rango de fechas");
        botonOp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOp1ActionPerformed(evt);
            }
        });

        botonOp2.setText("Cantidad de pacientes atendidos en un rango de fechas y edades");
        botonOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOp2ActionPerformed(evt);
            }
        });

        botonOp3.setText("Pacientes con mas consultas en un rango de fechas");
        botonOp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOp3ActionPerformed(evt);
            }
        });

        botonOp4.setText("Medico/s que mas pacientes haya/n atendido en un rango de fechas");
        botonOp4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOp4ActionPerformed(evt);
            }
        });

        botonOp5.setText("Triages realizados en un rango de fechas");
        botonOp5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOp5ActionPerformed(evt);
            }
        });

        botonOp6.setText("Cantidad de Triages que fueron cambiados por quien efectuó el Triage");
        botonOp6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOp6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonOp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonOp2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(botonOp3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(botonOp4, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(botonOp5, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(botonOp6, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(botonOp1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonOp2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonOp3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonOp4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonOp5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonOp6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOp1ActionPerformed
        Op1GestorCentro opcion1 = new Op1GestorCentro();
        opcion1.setVisible(true);
        opcion1.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonOp1ActionPerformed

    private void botonOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOp2ActionPerformed
        Op2GestorCentro opcion2 = new Op2GestorCentro();
        opcion2.setVisible(true);
        opcion2.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonOp2ActionPerformed

    private void botonOp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOp3ActionPerformed
        Op3GestorCentro opcion3 = new Op3GestorCentro();
        opcion3.setVisible(true);
        opcion3.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonOp3ActionPerformed

    private void botonOp4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOp4ActionPerformed
        Op4GestorCentro opcion4 = new Op4GestorCentro();
        opcion4.setVisible(true);
        opcion4.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonOp4ActionPerformed

    private void botonOp5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOp5ActionPerformed
        Op5GestorCentro opcion5 = new Op5GestorCentro();
        opcion5.setVisible(true);
        opcion5.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonOp5ActionPerformed

    private void botonOp6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOp6ActionPerformed
        Op6GestorCentro opcion6 = new Op6GestorCentro();
        opcion6.setVisible(true);
        opcion6.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_botonOp6ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonOp1;
    private javax.swing.JButton botonOp2;
    private javax.swing.JButton botonOp3;
    private javax.swing.JButton botonOp4;
    private javax.swing.JButton botonOp5;
    private javax.swing.JButton botonOp6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    // End of variables declaration//GEN-END:variables
}
